site_name: Zubair
site_url: https://stevepelhan.gitlab.io/
site_dir: public
docs_dir: ./Zubair
theme:
  name: material
  palette:
    scheme: slate
    primary: deep purple

plugins:
  - search
  - roamlinks

markdown_extensions:
    - def_list
    - pymdownx.tasklist:
        custom_checkbox: true